version: '3'

services:
  mariadb:
    volumes:
      - ./requirements/mariadb/mariadb-db:/db
    build: ./requirements/mariadb
    networks:
      - inception
    command: mariadbd
    restart: always
  # mariadb healthcheck하기
    # healthcheck: 
    #   test: exit 0 || exit 1
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3

  wordpress:
    volumes:
      - word:/wp/
    build:
      context: ./requirements/wordpress/
    networks:
      - inception
    command: ./mkdir.sh 
    depends_on:
      - mariadb
      # mariadb:
        # condition: service_healthy
    restart: always
    env_file:
      - .env
  # mariadb healthcheck하기
    # healthcheck: 
    #   test: exit 0 || exit 1
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3

  nginx:
    volumes:
      - word:/wp/
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    command: nginx -g "daemon off;"
    depends_on:
      - wordpress
      # wordpress:
        # condition: service_healthy
    restart: always

# TODO how to do?
volumes:
  word:
    driver: local
    driver_opts:
      o: bind
      type: none
      # device: /Users/juha/goinfre/data
      device: ./requirements/wordpress/data/

networks:
  inception:
