version: '3'


services:
  wordpress:
    volumes:
      - word:/var/www
    build:
      context: ./requirements/wordpress/
    networks:
      - inception
    command: php-fpm7.4 -F

  nginx:
    volumes:
      - word:/var/www
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    command: nginx -g "daemon off;"
    depends_on:
      - wordpress 

# TODO how to do?
volumes:
  db-data:
  word:

networks:
  inception: