version: '3'

services:
  # mariadb:
  #   volumes:
  #     - ./requirements/mariadb/mariadb-db:/db
  #   build: ./requirements/mariadb
  #   networks:
  #     - db 
  #   command: mariadbd
  #   restart: always

  wordpress:
    volumes:
      - word:/var/www
    build:
      context: ./requirements/wordpress/
    networks:
      - inception
      # - db
    command: php-fpm7.4 -F
    # depends_on:
      # - mariadb
    restart: always

  nginx:
    volumes:
      - word:/var/www
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    command: nginx -g "daemon off;"
    depends_on:
      - wordpress
    restart: always

# TODO how to do?
volumes:
  word:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /Users/juha/Desktop/42/inception/srcs/requirements/wordpress/wp-data

networks:
  inception:
  # db: