version: '3'

networks:
  inception:

services:
  wordpress:
    # volumes:
    #   - ./requirements/wordpress/data:/var/www
    build:
      context: ./requirements/wordpress/
    ports:
      - "9000"
    networks:
      - inception
    command: php-fpm7.4 -F

  nginx:
    volumes:
      - ./requirements/wordpress/data:/var/www
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    command: nginx -g "daemon off;"
    depends_on:
      - wordpress 


# TODO how to do?
# volumes:
  # db-data:
