version: '3'

services:
  nginx:
    image: nginx
    build:
      dockerfile: ./requirement/nginx/Dockerfile
    links: mariadb
    expose: 
      - "443"
    secrets:
      - server-certificate
    restart: always
    networks:
      - nginxne_net
      - mariadb_net
      - wordpress_net

  wordpress:
    image: wordpress
    build:
      dockerfile: ./requirement/wordpress/Dockerfile
    links: mariadb
    restart: always
    networks:
      - nginxne_net
      - mariadb_net
      - wordpress_net

  mariadb:
    image: mariadb
    build: 
      dockerfile: ./requirement/mariadb/Dockerfile
    env_file: .env
    restart: always
    networks:
      - nginxne_net
      - mariadb_net
      - wordpress_net

    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: /var/run/postgres/postgres.sock
        target: /var/run/postgres/postgres.sock

# TODO change security path
secrets:
  server-certificate:
    file: ./server.cert

volumes:
  db-data:

networks: