version: '3'

services:
  # mariadb:
  #   volumes:
  #     - ./
  #   build: ./requirements/mariadb
  #   networks:
  #     - inception
  #   command:
    # restart: always

  wordpress:
    volumes:
      - word:/var/www
    build:
      context: ./requirements/wordpress/
    networks:
      - inception
    command: php-fpm7.4 -F
    # depends_on:
      # - mariadb
    restart: always

  nginx:
    volumes:
      - word:/var/www
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    command: nginx -g "daemon off;"
    depends_on:
      - wordpress 
    restart: always

# TODO how to do?
volumes:
  db-data:
  word:

networks:
  inception:
  db: