version: '3'

services:
  mariadb:
    container_name: mariadb
    volumes:
      - ./requirements/mariadb/data:/var/lib/mysql
    build: ./requirements/mariadb
    networks:
      inception:
        aliases:
          - mariadb
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    volumes:
      - word:/var/www
    build:
      context: ./requirements/wordpress/
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env

  nginx:
    container_name: nginx
    volumes:
      - word:/var/www
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

# TODO how to do?
volumes:
  word:
    driver: local
    driver_opts:
      o: bind
      type: none
      # device: /Users/juha/goinfre/data
      device: ./requirements/wordpress/data/

networks:
  inception:
    driver: bridge
