version: '3'
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - inception
    command: nginx -g "daemon off;"

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    ports:
      - "9000"
    networks:
      - inception
      # - mariadb
    command: wordpress

# TODO how to do?
# volumes:
  # db-data:

networks:
  inception: